# This workflow goes in the PRIVATE repo (.github/workflows/release.yml)
# It builds binaries and publishes them to the PUBLIC repo

name: Build and Publish Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v0.1.0)'
        required: false

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS Apple Silicon
          - platform: macos-latest
            target: aarch64-apple-darwin
            name: macOS-arm64

          # Windows
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            name: Windows-x64

          # Linux
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            name: Linux-x64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      # Setup
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      # Build
      - name: Install frontend dependencies
        run: bun install --frozen-lockfile

      - name: Build Tauri app
        run: bun run tauri build --target ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts for release job
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
            src-tauri/target/${{ matrix.target }}/release/bundle/nsis/*.exe
            src-tauri/target/${{ matrix.target }}/release/bundle/appimage/*.AppImage
            src-tauri/target/${{ matrix.target }}/release/bundle/deb/*.deb
          if-no-files-found: ignore

  # Publish to PUBLIC repo
  publish-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: find artifacts -type f

      - name: Create Release on Public Repo
        uses: softprops/action-gh-release@v2
        with:
          repository: OutrageLabs/terX  # <-- PUBLIC REPO
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}  # <-- PAT with repo scope
          tag_name: ${{ github.ref_name }}
          name: 'terX ${{ github.ref_name }}'
          body: |
            ## Downloads

            | Platform | Architecture | File |
            |----------|--------------|------|
            | Windows | x64 | `.exe` installer |
            | macOS | Apple Silicon (M1/M2/M3/M4) | `.dmg` |
            | Linux | x64 | `.AppImage` / `.deb` |

            ---

            **First time on macOS?** Right-click → Open (bypass Gatekeeper)

            **Linux AppImage:**
            ```bash
            chmod +x terx_*.AppImage
            ./terx_*.AppImage
            ```

            See [CHANGELOG.md](https://github.com/OutrageLabs/terX/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
          files: |
            artifacts/**/*.dmg
            artifacts/**/*.exe
            artifacts/**/*.AppImage
            artifacts/**/*.deb

  # Update CHANGELOG in public repo
  update-changelog:
    needs: publish-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: OutrageLabs/terX  # <-- PUBLIC REPO
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          ref: main

      - name: Checkout private repo CHANGELOG
        uses: actions/checkout@v4
        with:
          path: private-repo
          sparse-checkout: CHANGELOG.md
          sparse-checkout-cone-mode: false

      - name: Copy CHANGELOG to public repo
        run: cp private-repo/CHANGELOG.md CHANGELOG.md

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          file_pattern: CHANGELOG.md
